package gov.nci.ppe.constants;

public enum PPERole {
	ROLE_PPE_CRC, ROLE_PPE_PROVIDER, ROLE_PPE_PARTICIPANT, ROLE_PPE_ADMIN, ROLE_PPE_BSSC, ROLE_PPE_MOCHA_ADMIN,
	ROLE_PPE_CONTENT_EDITOR, ROLE_PPE_MESSENGER;

}
